# Generated by Django 4.2.1 on 2023-06-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attribute1', models.CharField(max_length=100)),
                ('attribute2', models.IntegerField()),
                ('attribute3', models.BooleanField()),
                ('attribute4', models.DateField()),
            ],
        ),
    ]
