# Generated by Django 4.2.1 on 2023-06-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('item_name', models.CharField(max_length=40)),
                ('quantity', models.PositiveBigIntegerField()),
                ('total_price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date_added', models.DateField()),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
