# Generated by Django 3.2.12 on 2023-08-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_image',
            field=models.ImageField(null=True, upload_to='cart_images/'),
        ),
    ]
